//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniERP.Quotation {
    
    
    public partial class ContractorQuotation {
        
        /// <summary>
        /// tbc_quotation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.TabContainer tbc_quotation;
        
        /// <summary>
        /// tbpnl_quotation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.TabPanel tbpnl_quotation;
        
        /// <summary>
        /// QuotationControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MiniERP.Parts.Quotation QuotationControl;
        
        /// <summary>
        /// tbpnl_DeliverySchedule control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.TabPanel tbpnl_DeliverySchedule;
        
        /// <summary>
        /// DeliveryControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MiniERP.Quotation.Parts.DeliveryScheduleContractor DeliveryControl;
        
        /// <summary>
        /// tbpnl_PaymentTerms control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.TabPanel tbpnl_PaymentTerms;
        
        /// <summary>
        /// PaymentControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MiniERP.Parts.PaymentTerms PaymentControl;
        
        /// <summary>
        /// tbpnl_TermConditions control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.TabPanel tbpnl_TermConditions;
        
        /// <summary>
        /// TermConditionControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MiniERP.Parts.TermConditions TermConditionControl;
    }
}
