//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniERP.IssueMaterial {
    
    
    public partial class IssuingMaterial {
        
        /// <summary>
        /// Issuing_Material control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MiniERP.Quality.Parts.IssuingMaterial Issuing_Material;
    }
}
